project:
  type: website

website:
  title: "Shannon Fernandes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: interests/psychology.qmd
        text: Psychology
      - href: interests/coding.qmd
        text: Coding
      - href: interests/writing.qmd
        text: Writing
      - href: interests/design.qmd
        text: Design

format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.css
